package com.anding.shipvideo.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.anding.shipvideo.data.CategorySub;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATEGORY_SUB".
*/
public class CategorySubDao extends AbstractDao<CategorySub, Void> {

    public static final String TABLENAME = "CATEGORY_SUB";

    /**
     * Properties of entity CategorySub.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Category = new Property(0, String.class, "category", false, "CATEGORY");
        public final static Property Value = new Property(1, String.class, "value", false, "VALUE");
        public final static Property Label = new Property(2, String.class, "label", false, "LABEL");
    }


    public CategorySubDao(DaoConfig config) {
        super(config);
    }
    
    public CategorySubDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATEGORY_SUB\" (" + //
                "\"CATEGORY\" TEXT," + // 0: category
                "\"VALUE\" TEXT," + // 1: value
                "\"LABEL\" TEXT);"); // 2: label
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATEGORY_SUB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CategorySub entity) {
        stmt.clearBindings();
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(1, category);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(2, value);
        }
 
        String label = entity.getLabel();
        if (label != null) {
            stmt.bindString(3, label);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CategorySub entity) {
        stmt.clearBindings();
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(1, category);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(2, value);
        }
 
        String label = entity.getLabel();
        if (label != null) {
            stmt.bindString(3, label);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public CategorySub readEntity(Cursor cursor, int offset) {
        CategorySub entity = new CategorySub( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // category
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // value
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // label
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CategorySub entity, int offset) {
        entity.setCategory(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setValue(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLabel(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(CategorySub entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(CategorySub entity) {
        return null;
    }

    @Override
    public boolean hasKey(CategorySub entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
