package com.anding.shipvideo.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.anding.shipvideo.data.Video;
import com.anding.shipvideo.data.VideoReal;

import com.anding.shipvideo.database.VideoDao;
import com.anding.shipvideo.database.VideoRealDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoDaoConfig;
    private final DaoConfig videoRealDaoConfig;

    private final VideoDao videoDao;
    private final VideoRealDao videoRealDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        videoRealDaoConfig = daoConfigMap.get(VideoRealDao.class).clone();
        videoRealDaoConfig.initIdentityScope(type);

        videoDao = new VideoDao(videoDaoConfig, this);
        videoRealDao = new VideoRealDao(videoRealDaoConfig, this);

        registerDao(Video.class, videoDao);
        registerDao(VideoReal.class, videoRealDao);
    }
    
    public void clear() {
        videoDaoConfig.clearIdentityScope();
        videoRealDaoConfig.clearIdentityScope();
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

    public VideoRealDao getVideoRealDao() {
        return videoRealDao;
    }

}
